[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.2",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "geoalchemy2>=0.20.0",
    "psycopg>=3.3.5",
    "redis>=8.1.0",
    "scalar-fastapi>=1.9.0",
    "shapely>=2.1.2",
    "sqlalchemy>=2.0.52",
    "websockets>=17.1",
]

