"""add column for fecha_hora_comienzo in AsignacionRuta

Revision ID: 3beda3bf0204
Revises: 907ce7268d40
Create Date: 2026-09-11 18:09:49.699214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3beda3bf0204'
down_revision: Union[str, Sequence[str], None] = '907ce7268d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignacion_ruta', sa.Column('fecha_hora_comienzo', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asignacion_ruta', 'fecha_hora_comienzo')
    # ### end Alembic commands ###
