"""add idempotency key to conductor

Revision ID: 907ce7268d40
Revises: dd770df9fa5b
Create Date: 2026-09-10 18:22:17.429212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907ce7268d40'
down_revision: Union[str, Sequence[str], None] = 'dd770df9fa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conductor', sa.Column('idempotency_key', sa.UUID(), nullable=False))
    op.create_unique_constraint(op.f('uq_conductor_idempotency_key'), 'conductor', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_conductor_idempotency_key'), 'conductor', type_='unique')
    op.drop_column('conductor', 'idempotency_key')
    # ### end Alembic commands ###
