"""add administrator table

Revision ID: 9251248169c3
Revises: d33ad35776c3
Create Date: 2026-09-06 18:32:41.478048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9251248169c3'
down_revision: Union[str, Sequence[str], None] = 'd33ad35776c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradores',
    sa.Column('id_administrador', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_administrador', name=op.f('pk_administradores')),
    sa.UniqueConstraint('email', name=op.f('uq_administradores_email'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administradores')
    # ### end Alembic commands ###
