"""fix representante foreign key

Revision ID: dd770df9fa5b
Revises: 9251248169c3
Create Date: 2026-09-06 20:16:52.018346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd770df9fa5b'
down_revision: Union[str, Sequence[str], None] = '9251248169c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_grupo_operativo_nombre_grupo'), 'grupo_operativo', ['nombre_grupo'])
    op.create_foreign_key('fk_grupo_operativo_representante', 'grupo_operativo', 'conductor', ['id_representante'], ['id_conductor'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_grupo_operativo_representante', 'grupo_operativo', type_='foreignkey')
    op.drop_constraint(op.f('uq_grupo_operativo_nombre_grupo'), 'grupo_operativo', type_='unique')
    # ### end Alembic commands ###
